parameters:
    locale: en
    secret: ekonf9935ty43576hbfhfo3e856t
    session_name: koala_session
    session_remember_me_name: koala_session_remember
    session_max_idle_time: 900
    country: AU
    sign_in_count_minimum: 3
    sign_in_ip_exceptions: {  }
    timezone: Australia/Sydney
    password_min_length: 8
    password_numbers: 1
    password_mixed_case: 1
    password_specials: 0
    hemisphere: South
    person_identifier_index: 180301LB
