doctrine:
    dbal:
        connections:
            gibbon:
                driver:   '%db_driver%'
                host:     '%db_host%'
                port:     '%db_port%'
                dbname:   '%db2_name%'
                user:     '%db_user%'
                password: '%db_pass%'
                charset:  '%db_charset%'
                default_table_options:
                    charset: utf8mb4
                    collate: utf8mb4_unicode_ci
                server_version: '5.5'
    orm:
        entity_managers:
            gibbon:
                connection: gibbon
