language: php

matrix:
    include:
        - php: 7.2
    fast_finish: true
addons:
    mariadb: 10.2

notifications:
    email: craig@craigrayner.com

before_install:
    # turn off XDebug
    - phpenv config-rm xdebug.ini || return 0

install:
    - travis_retry composer install
