language: php

matrix:
    include:
        - php: 7.2
    fast_finish: true

notifications:
    email: craig@craigrayner.com

before_install:
    # turn off XDebug
    - phpenv config-rm xdebug.ini || return 0

install:
    - travis_retry composer install
    - cp /config/packages/doctrine.yaml.travis /config/packages/doctrine.yaml
    - php bin/console doctrine:database:create --env=test
    - php bin/console doctrine:schema:create --env=test

# Allows use container-based infrastructure
sudo: false

services:
    - mysql

# Cache composer packages so "composer install" is faster
cache:
    directories:
        - $HOME/.composer/cache/files

# Define an environment variable
env:
    - SYMFONY_VERSION="4.0.*" DB=mariadb

# Run script
script:
    - phpunit
