controllers:
    resource: ../../src/Controller/
    prefix:   /{_locale}
    requirements:
        _locale: en
    defaults: { _locale: en}
    type: annotation
core:
    resource: ../../src/Core/Controller/
    type: annotation
