<?php
namespace App\Repository;

use App\Entity\Activity;
use App\Entity\CalendarGrade;
use Doctrine\Bundle\DoctrineBundle\Repository\ServiceEntityRepository;
use Symfony\Bridge\Doctrine\RegistryInterface;

/**
 * ActivityRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ActivityRepository extends ServiceEntityRepository
{
	/**
	 * AddressRepository constructor.
	 *
	 * @param RegistryInterface $registry
	 */
	public function __construct(RegistryInterface $registry)
	{
		parent::__construct($registry, Activity::class);
	}

    /**
     * @param string $name
     * @param CalendarGrade $calendarGrade
     * @return Activity|null
     * @throws \Doctrine\ORM\NonUniqueResultException
     */
    public function seekCalendarGradeName(string $name, CalendarGrade $calendarGrade): ?Activity
    {
        return $this->createQueryBuilder('a')
            ->leftJoin('a.calendarGrades', 'cg')
            ->where('cg.id = :cg_id')
            ->setParameter('cg_id', $calendarGrade->getId())
            ->andWhere('a.name = :name')
            ->setParameter('name', $name)
            ->getQuery()
            ->getOneOrNullResult()
        ;
    }
}
