<?php
namespace App\Repository;

use App\Entity\Address;
use Doctrine\Bundle\DoctrineBundle\Repository\ServiceEntityRepository;
use Symfony\Bridge\Doctrine\RegistryInterface;

/**
 * AddressRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AddressRepository extends ServiceEntityRepository
{
	/**
	 * AddressRepository constructor.
	 *
	 * @param RegistryInterface $registry
	 */
	public function __construct(RegistryInterface $registry)
	{
		parent::__construct($registry, Address::class);
	}
	/**
	 * get Locality Choices
	 *
	 * @version    29th October 2016
	 * @since      29th October 2016
	 * @return    array    hint=>value
	 */
	public function getAddressChoices()
	{
		$x      = $this->findBy(array(), array('propertyName' => 'ASC', 'streetName' => 'ASC'));
		$result = array();
		foreach ($x as $w)
		{
			$key          = trim($w->getPropertyName() . ' ' . $w->getBuildingType() . ' ' . $w->getBuildingNumber() . '/' . $w->getStreetNumber() . ' ' . $w->getStreetName(), ' /');
			$result[$key] = $w->getId();
		}

		return $result;
	}

	/**
	 * find
	 *
	 * @param      $id
	 * @param null $lockMode
	 * @param null $lockVersion
	 *
	 * @return Address
	 */
	public function find($id, $lockMode = null, $lockVersion = null)
	{
		if (is_null($id))
			return new Address();

		return parent::find($id, $lockMode, $lockVersion);
	}
}
