<?php
namespace App\Repository;
use App\Entity\DepartmentMember;
use Doctrine\Bundle\DoctrineBundle\Repository\ServiceEntityRepository;
use Symfony\Bridge\Doctrine\RegistryInterface;

/**
 * DepartmentMemberRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DepartmentMemberRepository extends ServiceEntityRepository
{
	public function __construct(RegistryInterface $registry)
	{
		parent::__construct($registry, DepartmentMember::class);
	}
	public function findByStaffCoordinator(Staff $staff)
	{
		return $this->createQueryBuilder('d')
			->leftJoin('d.staff', 's')
			->where('s.id = :staff_id')
			->setParameter('staff_id', $staff->getId())
			->andWhere('d.staffType LIKE :staffType')
			->setParameter('staffType', '%Coordinator%')
			->getQuery()
			->getResult();
	}
}
