<?php
namespace App\Repository;

use App\Entity\Family;
use Doctrine\Bundle\DoctrineBundle\Repository\ServiceEntityRepository;
use Symfony\Bridge\Doctrine\RegistryInterface;

/**
 * FamilyRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FamilyRepository extends ServiceEntityRepository
{
	/**
	 * FamilyRepository constructor.
	 *
	 * @param RegistryInterface $registry
	 */
	public function __construct(RegistryInterface $registry)
	{
		parent::__construct($registry, Family::class);
	}

	/**
	 * @param mixed $id
	 * @param null  $lockMode
	 * @param null  $lockVersion
	 *
	 * @return Family
	 */
	public function find($id, $lockMode = null, $lockVersion = null): Family
	{
		$family = parent::find($id, $lockMode, $lockVersion);

		return $family instanceof Family ? $family : new Family();
	}

	/**
	 * @param $person
	 *
	 * @return mixed
	 */
	public function findByStudentsPerson($person)
	{
		$result = $this->createQueryBuilder('f')
			->leftJoin('f.students', 's')
			->where('s.id = :student')
			->setParameter('student', $person->getId())
			->getQuery()
			->getResult();
		return $result;
	}

	/**
	 * @param $person
	 *
	 * @return mixed
	 */
	public function findByCareGiverPerson($person)
	{
		$result = $this->createQueryBuilder('f')
			->leftJoin('f.careGivers', 'c')
			->leftJoin('c.person', 'p')
			->where('p.id = :person_id')
			->setParameter('person_id', $person->getId())
			->getQuery()
			->getResult();

		return $result;
	}

}
