<?php
namespace App\Repository;

use App\Entity\Page;
use Doctrine\Bundle\DoctrineBundle\Repository\ServiceEntityRepository;
use Symfony\Bridge\Doctrine\RegistryInterface;

/**
 * PageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PageRepository extends ServiceEntityRepository
{
	public function __construct(RegistryInterface $registry)
	{
		parent::__construct($registry, Page::class);
	}

	public function findOneByRoute($routeName): Page
	{
		$page = parent::findOneByRoute($routeName);

		if (empty($page))
		{
			$page = new Page();
			$page->setRoute($routeName);
			$page->setCacheTime();
		}

		return $page;
	}
}
