<?php
namespace App\Repository;

use App\Entity\RollGroup;
use Doctrine\Bundle\DoctrineBundle\Repository\ServiceEntityRepository;
use Symfony\Bridge\Doctrine\RegistryInterface;

/**
 * Student Calendar Group Repository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RollGroupRepository extends ServiceEntityRepository
{
	/**
	 * RollGroupRepository constructor.
	 *
	 * @param RegistryInterface $registry
	 */
	public function __construct(RegistryInterface $registry)
	{
		parent::__construct($registry, RollGroup::class);
	}

    /**
     * @param int:string $id
     * @param null $lockMode
     * @param null $lockVersion
     * @return RollGroup|null|object
     */
    public function find($id, $lockMode = null, $lockVersion = null)
    {
        return $id === 'Add' ? new RollGroup() : parent::find($id, $lockMode, $lockVersion);
    }
}
