App\Entity\ActivityStudent:
    constraints:
        - Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity:
            fields: [activity, student]
            message: activity.student.validation.duplicate
    fields:
        activity:
            - NotBlank: ~
        student:
            - NotBlank: ~
