App\Entity\ActivityTutor:
    constraints:
        - Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity:
            fields: [tutor, activity]
            errorPath: role
            message: tutor.activity.link.duplicate
        - Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity:
            fields: [sequence, activity]
            errorPath: role
            message: tutor.activity.sequence.duplicate
    properties:
        sequence:
            - NotBlank: ~
        activity:
            - NotBlank: ~
        tutor:
            - NotBlank: ~