App\Entity\Course:
    properties:
        department:
            - Valid: ~
            - NotBlank: ~
        calendarGrades:
            - Valid: ~
            - Count:
                min: 1
        code:
            - NotBlank: ~
            - Length:
                max: 8
        name:
            - NotBlank: ~
