App\Entity\Department:
    properties:
        members:
            - Valid: ~
        name:
            - NotBlank: ~
        nameShort:
            - NotBlank: ~
            - Length:
                max: 4
