App\Entity\DepartmentMember:
    constraints:
        - Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity:
            fields:
                - staff
                - department
    properties:
        staffType:
            - App\Core\Validator\SettingChoice:
                settingName: 'department.staff.type.list'