App\Entity\Phone:
    constraints:
        - Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity:
            fields: [phoneNumber, countryCode, phoneType]
            errorPath: phoneNumber
    properties:
        phoneNumber:
            - NotBlank: ~
            - App\People\Validator\Phone: ~
        phoneType:
            - NotBlank: ~
        countryCode:
            - NotBlank: ~
