App\Entity\Phone:
    constraints:
        - Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity:
            fields: [phoneNumber, countryCode, phoneType]
            errorPath: phoneNumber
    properties:
        phoneNumber:
            - NotBlank: ~
            - \App\People\Validator\Phone: ~
        phoneType:
            - NotBlank: ~
            - \App\Core\Validator\SettingChoice:
                name: 'phone.type.list'
        countryCode:
            - NotBlank: ~
            - \App\Core\Validator\SettingChoice:
                name: 'phone.country.list'
