App\Entity\RollGroup:
    constraints:
        - Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity:
            fields:
                - nameShort
                - calendar
            errorPath: nameShort
        - Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity:
            fields:
                - name
                - calendar
            errorPath: name
        - Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity:
            fields:
                - space
                - calendar
            errorPath: space
    properties:
        website:
            - Url: ~
        name:
            - NotBlank: ~
        nameShort:
            - NotBlank: ~
        calendar:
            - Valid: ~
            - NotBlank: ~
        grade:
            - NotBlank: ~