App\Entity\Setting:
    constraints:
        - Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity:
            fields: [name]
            errorPath: name
            message: 'unique.setting.name'
    properties:
        validator:
            - App\Core\Validator\FileExists:
                transDomain: 'Setting'
                message: setting.validator.class.error
        name:
            - NotBlank: ~
        displayName:
            - NotBlank: ~