App\Entity\Setting:
    constraints:
        - Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity:
            fields: [name]
            errorPath: name
            message: 'unique.setting.name'
