App\Entity\SpecialDay:
    constraints:
        - Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity: 
            fields: [day]
            errorPath: day
            message: 'Each date must be unique to the Special Day record.'
    properties:
        name:
            - NotBlank: ~
        calendar:
            - NotBlank: ~
        type:
            - Hillrange\Form\Validator\Enum:
                class: App\Entity\SpecialDay
                method: getTypeList