App\Entity\Student:
    constraints:
        - App\People\Validator\StudentCalendarGrades: ~
    properties:
        startAtSchool:
            - Date: ~
        startAtThisSchool:
            - Date: ~
        lastAtThisSchool:
            - Date: ~
        citizenship1PassportScan:
            - App\People\Validator\PassportImage: ~
        nationalIDCardScan:
            - App\People\Validator\PassportImage: ~
