App\Entity\Student:
    constraints:
        - App\People\Validator\StudentCalendarGrades: ~
    properties:
        startAtSchool:
            - Date: ~
        startAtThisSchool:
            - Date: ~
        lastAtThisSchool:
            - Date: ~
        house:
            - App\Core\Validator\SettingChoice:
                settingName: 'house.list'
                settingDataValue: 'name'
        citizenship1PassportScan:
            - App\People\Validator\PassportImage: ~
        nationalIDCardScan:
            - App\People\Validator\PassportImage: ~
