App\Entity\Student:
    properties:
        startAtSchool:
            - Date: ~
        startAtThisSchool:
            - Date: ~
        lastAtThisSchool:
            - Date: ~
        house:
            - App\Core\Validator\SettingChoice:
                name: 'house.list'
        citizenship1PassportScan:
            - \App\People\Validator\PassportImage: ~
        nationalIDCardScan:
            - \App\People\Validator\PassportImage: ~
