App\Entity\Term:
    constraints:
        - Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity: 
            fields: [name, calendar]
            errorPath: name
            message: 'The Term Name must be unique within the year.'
        - Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity: 
            fields: [code, calendar]
            errorPath: code
            message: 'The term Short Name must be unique within the year.'
    properties:
        name:
            - NotBlank: ~
        code:
            - NotBlank: ~
        calendar:
            - NotBlank: ~