App\Entity\TimetableColumnPeriod:
    constraints:
        - Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity:
            fields:
                - name
                - column
            errorPath: name
        - Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity:
            fields:
                - code
                - column
            errorPath: code
    properties:
        name:
            - NotBlank: ~
            - Length:
                max: 12
        code:
            - NotBlank: ~
            - Length:
                max: 4
        type:
            - App\Core\Validator\SettingChoice:
                name: period.type.list
        timeStart:
            - NotBlank: ~
        timeEnd:
            - NotBlank: ~
