App\Entity\TimetableColumn:
    constraints:
        - Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity:
            fields:
                - name
                - timetable
            errorPath: name
        - Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity:
            fields:
                - code
                - timetable
            errorPath: code
        - Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity:
            fields:
                - sequence
                - timetable
            errorPath: name
    properties:
        name:
            - NotBlank: ~
            - Length:
                max: 30
        code:
            - NotBlank: ~
            - Length:
                max: 12
