App\Entity\Timetable:
    constraints:
        - Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity:
            fields:
                - name
                - calendar
            errorPath: name
        - Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity:
            fields:
                - code
                - calendar
            errorPath: code
    properties:
        name:
            - NotBlank: ~
        code:
            - NotBlank: ~
            - Length:
                max: 12
        calendar:
            - Valid: ~
        calendarGrades:
            - Valid: ~
